name: Deploy To Azure

on: 
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install Dependencies
        run: cd NovaAplicacao && npm install
      - name: Deploy on Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: Devops-CI-CD-Juliana
          publish-profile: '${{ secrets.AZURE_PUBLISH_PROFILE }}'
          package: ./NovaAplicacao